# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fca88e59f3a2bcafc8423afb3b38734826a6f5d930357a8ce31b934cd2da5045d4bc4ea51946c4ec41b2ba71f440a201f34adfaabe1b569e22a37406e74f361

test:
  secret_key_base: 5d5c74c2fc72ccbed4d37447cd78caafc1b6820acfb6dbcd9774ed8c7c66138f7848e00a79ffd1ada95944a749ac650acf96aa0ac3dbb6791765e9d77098186e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
